### ISSUE TITLE
nior4r requires Ruby version >= 2.3

### ISSUE THREAD

**Issue by rverchere** [sclorg/ruby-ex#36]
Hi,

when using last commit, the build fails:

```
Fetching gem metadata from https://rubygems.org/...
Gem::InstallError: nio4r requires Ruby version >= 2.3.
An error occurred while installing nio4r (2.5.2), and Bundler cannot continue.
Make sure that `gem install nio4r -v '2.5.2'` succeeds before bundling.
```

When using old commit it's fine:

```
source:
    git:
      ref: c00ecd7
      uri: https://github.com/openshift/ruby-ex.git
```
